package com.seleniumsimplified.webdriver.siteabstractions;

public enum PAGE_NAME {
    FRAMES_TEST_PAGE,
    BASIC_HTML_FORM_PAGE,
    FIND_BY_PLAYGROUND_PAGE,
    BASIC_WEB_PAGE,
    BASIC_AJAX_PAGE,
    ALERTS_PAGE,
    JAVASCRIPT_COUNTDOWN,
    FAKE_ALERTS_TEST_PAGE,
    IFRAMES_TEST_PAGE,
    WINDOW_SIZE_MEDIA_QUERIES_TEST_PAGE,
    WINDOW_LINKS_TEST_PAGE,
    SEARCH_ENGINE_PAGE,
    BASIC_REDIRECT_PAGE,
    BASIC_CALCULATOR_PAGE,
    BASIC_GUI_INTERACTIONS,
    USER_AGENT_REDIRECT,
    CANVAS_BASIC_TEST_PAGE,
    COMPLEX_IFRAMES_TEST_PAGE,
}
