name: build
on:
  push:
  workflow_dispatch:

env:
  BROWSER_STATE: Headless

jobs:
  compile-and-test-webdriver-4:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Download repository
        uses: actions/checkout@v3

      # https://github.com/actions/setup-java
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18

      - name: setup chrome
        uses: browser-actions/setup-chrome@v1

      - run: chrome --version

      - name: Test with Maven using Chrome
        working-directory: ./code/selenium_4/code
        run: mvn test -Dselenium2basics.webdriver=CHROME
